# run-tertiary-msea.R — reproduce the manuscript's Table S2 (tertiary MSEA) using
# the ORA / over-representation module + a name-matched reference metabolome
# (the actual method behind Table S2, not the pathway module). Runs combined and
# stratified arms; signs the enrichment ratio by direction (down = negative).
# Writes results/metaboanalyst/tertiary_msea/.
suppressMessages({ library(dplyr); library(readr); library(stringr) })
source("src/metaboanalyst/R/label-map.R")
source("src/metaboanalyst/R/build-cells.R")
source("src/metaboanalyst/R/run-ora.R")
source("src/metaboanalyst/R/harvest.R")
source("src/metaboanalyst/R/build-reference.R")

# Read the repo's OWN ATE output (regenerated by src/2 analysis/*; byte-identical to
# Trenton's provided copy) so the pipeline is raw -> ATE -> MetaboAnalyst end-to-end.
COMBINED_RDS   <- "results/combined_intervention_effects_results_combined_arms.RDS"
STRATIFIED_RDS <- "results/combined_intervention_effects_results_stratified_arms.RDS"
OUT <- "results/metaboanalyst/tertiary_msea"

# The cell's `study` field is a "Study (time point)" label. .study_label maps the
# study part to its published cohort name; .timepoint pulls out the parenthetical.
.study_label <- function(studytime) {
  study_name <- str_replace(studytime, "\\s*\\(.*$", "")
  dplyr::recode(study_name, "Misame" = "MISAME-III", "Vital" = "Mumta-LW", "Elicit" = "ELICIT",
                .default = study_name)
}
.timepoint <- function(studytime) {
  inside_parens <- str_replace(studytime, "^[^(]*\\(", "")   # drop up to "("
  str_trim(str_replace(inside_parens, "\\)\\s*$", ""))       # drop closing ")"
}

run_tertiary_msea <- function(dat, arm_set, ref, write = TRUE, out_suffix = "") {
  cells <- build_cells(dat, "tertiary")
  enrichment_rows <- list()
  for (cell in cells) {
    mSet <- tryCatch(run_ora(cell$query, reference_names = ref), error = function(e) NULL)
    if (is.null(mSet)) next
    res <- harvest_results(mSet)   # FULL per-cell table: every pathway with >=1 hit
    if (!nrow(res)) next
    # Sign the enrichment ratio by direction so downregulated cells read negative.
    res <- res %>% mutate(
      enrichment_ratio = ifelse(cell$direction == "down", -1, 1) * (hits / expected),
      study     = .study_label(cell$study),
      timepoint = .timepoint(cell$study),
      contrast  = cell$contrast,
      direction = cell$direction,
      arm_set   = arm_set)
    enrichment_rows[[length(enrichment_rows) + 1]] <- res
  }
  # This is the FULL, unfiltered pathway table (all pathway x cell rows with >=1
  # hit, significant AND non-significant). It is the single source of truth: the
  # figure draws its grey non-significant cloud from it, and manuscript Table S4
  # is a subset (fdr_native < 0.05) derived downstream -- nothing is hand-edited.
  msea_table <- bind_rows(enrichment_rows) %>%
    transmute(study, timepoint, contrast, direction, pathway,
              total, expected, hits, raw_p, fdr_native = fdr, enrichment_ratio) %>%
    # No size floor (min_size = 1), matching Trenton's ORA and the dual runner used by
    # Fig 5B so the reported tertiary table retains any 1-2 member lipid sets his
    # submission shows. fdr_native is MetaboAnalyst's own per-cell BH (over the full SMPDB
    # library) -- NOT recomputed on the surviving rows (that would inflate it).
    apply_pathway_size_floor(min_size = 1) %>%
    arrange(raw_p)
  if (isTRUE(write)) {
    dir.create(OUT, recursive = TRUE, showWarnings = FALSE)
    write_csv(msea_table, file.path(OUT, paste0("tertiary_msea_", arm_set, out_suffix, ".csv")))
    # Table S4 = FDR-significant subset (per-contrast MetaboAnalyst BH), derived here.
    write_csv(dplyr::filter(msea_table, fdr_native < 0.05),
              file.path(OUT, paste0("tertiary_msea_", arm_set, out_suffix, "_perContrastFDRsig_tableS4.csv")))
  }
  msea_table
}

if (sys.nframe() == 0) {
  combined   <- readRDS(COMBINED_RDS)
  stratified <- readRDS(STRATIFIED_RDS)

  # --- CONSERVATIVE (self) reference -----------------------------------------
  # The measured tertiary metabolites themselves, name-matched. This is the
  # narrow background (~self); it yields the sugar/nucleotide pathways and no
  # FDR-significant amino-acid signal.
  tertiary_metabolite_names <- combined %>%
    filter(outcome_group == "tertiary", measure == "ATE") %>%
    mutate(lab = apply_label_map(label_f)) %>% filter(!str_starts(lab, "Total")) %>%
    distinct(lab) %>% pull(lab)
  # build_matched_reference() does name-matching only (ORA matches by name, not KEGG id);
  # the former `kegg_cache_path` argument was removed when the function was refactored, so
  # passing it here raised "unused argument" and aborted the script before any ORA ran.
  ref_self <- build_matched_reference(tertiary_metabolite_names,
                                 cache_path = file.path(OUT, "tertiary_reference_matched.txt"))
  message("conservative (self) reference: ", length(ref_self), " of ",
          length(tertiary_metabolite_names), " raw names")

  # --- REFERENCE METABOLOME (1,593 HMDB -> 615 library names) -----------------
  # The author's saved reference metabolome (metabolites + lipids), NOT the whole
  # human metabolome (this file was previously mis-named "whole_metabolome").
  # Built by src/metaboanalyst/build-reference-metabolome.R. This 615-name variant
  # is the smaller relative of the QER reference below.
  REF_METAB <- "src/metaboanalyst/reference/reference_metabolome_1593_matched_names.txt"
  ref_metabolome <- trimws(readLines(REF_METAB, warn = FALSE)); ref_metabolome <- ref_metabolome[ref_metabolome != ""]
  message("reference metabolome (1,593-HMDB variant): ", length(ref_metabolome), " names")

  # --- QER reference metabolome (the ACTUAL submitted MetaboAnalyst-web upload) -
  # refMetabolomeForQER.csv is the author's saved metabolites+lipids reference
  # uploaded to the web tool for the submitted 5B run. It is a curated name list
  # (~1,268 unique names), LARGER than the 615-name variant, giving a bigger
  # effective N (smaller expected -> more FDR-significant pathways). This is the
  # submission-matching background (confirmed on the 2026-08-13 call); the dual
  # runner run-tertiary-msea-dual.R uses it to recover 16/20 submitted pathways.
  QER_REF <- "src/metaboanalyst/reference/refMetabolomeForQER.csv"
  ref_qer <- trimws(readLines(QER_REF, warn = FALSE)); ref_qer <- unique(ref_qer[ref_qer != ""])
  message("QER reference metabolome (submission-matching): ", length(ref_qer), " names")

  # DEFAULT outputs (no suffix) use the 1,593-HMDB reference-metabolome variant.
  # The conservative variant carries a "_conservative" suffix; the QER
  # (submission-matching) reference carries a "_QERref" suffix.
  run_tertiary_msea(combined,   "combined",   ref_metabolome)
  run_tertiary_msea(stratified, "stratified", ref_metabolome)
  run_tertiary_msea(combined,   "combined",   ref_self, out_suffix = "_conservative")
  run_tertiary_msea(stratified, "stratified", ref_self, out_suffix = "_conservative")
  run_tertiary_msea(combined,   "combined",   ref_qer,  out_suffix = "_QERref")
  run_tertiary_msea(stratified, "stratified", ref_qer,  out_suffix = "_QERref")
  message("done: wrote tertiary_msea_{combined,stratified}[_conservative|_QERref].csv")
}
